name: Nx CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        node_version:
          # - 12
          - 14
          - 15
        package_manager:
          - npm
          - yarn
        packages:
          - e2e-workspace
          - e2e-cli,e2e-nx-plugin,dep-graph-client-e2e
          - e2e-cypress,e2e-jest
          - e2e-react
          - e2e-next
          - e2e-node
          - e2e-web,e2e-linter,e2e-storybook

    name: Node v${{ matrix.node_version }} on ${{ matrix.os }} - ${{ matrix.packages }}  with ${{ matrix.package_manager }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install

    - name: Install PNPM
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.13.5

    - name: Run E2E
      run: yarn e2e ${{ matrix.packages }} affected
      env:
        NODE_OPTIONS: --max_old_space_size=4096
        SELECTED_PM: ${{ matrix.package_manager }}
        CI: true