name: Nx CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          # - ubuntu-latest
          # - macos-latest
          - windows-latest
        node_version:
          # - 10
          - 12
          # - 14

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn


    - name: Run Local Npm Registry (Verdaccio) On Windows
    run: |
      npm install --global forever
      forever start node_modules\verdaccio\bin\verdaccio --config ./verdaccio/conf/default.yaml

    - run: yarn e2e-tests e2e-next
      env:
        CI: true